from rapidfuzz import fuzz

# fmt: off
KNOWN_MERCHANTS: dict[str, tuple[str, str, float]] = {

    # ── Food Delivery ─────────────────────────────────────────────────────────
    "SWIGGY":                               ("Swiggy",          "Food", 0.99),
    "Swiggy":                               ("Swiggy",          "Food", 0.99),
    "SWIGGY INSTAMART":                     ("Swiggy Instamart","Groceries", 0.99),
    "BUNDL TECHNOLOGIES PRIVATE LIMITED":   ("Swiggy",          "Food", 0.99),
    "ZOMATO":                               ("Zomato",          "Food", 0.99),
    "Zomato":                               ("Zomato",          "Food", 0.99),
    "ZOMATO LIMITED":                       ("Zomato",          "Food", 0.99),
    "BLINKIT":                              ("Blinkit",         "Groceries", 0.99),
    "GROFERS INDIA PRIVATE LIMITED":        ("Blinkit",         "Groceries", 0.99),
    "DUNZO":                                ("Dunzo",           "Groceries", 0.99),
    "DUNZO DIGITAL PRIVATE LIMITED":        ("Dunzo",           "Groceries", 0.99),
    "DOMINOS PIZZA":                        ("Domino's",        "Food", 0.99),
    "DOMINO'S PIZZA":                       ("Domino's",        "Food", 0.99),
    "Dominos Pizza":                        ("Domino's",        "Food", 0.99),
    "PIZZA HUT":                            ("Pizza Hut",       "Food", 0.99),
    "YUMINGLABS PRIVATE LIMITED":           ("Wow Momo",        "Food", 0.95),
    "MCDONALDS":                            ("McDonald's",      "Food", 0.99),
    "HARDCASTLE RESTAURANTS":               ("McDonald's",      "Food", 0.99),
    "KFC":                                  ("KFC",             "Food", 0.99),
    "DEVYANI INTERNATIONAL":                ("KFC",             "Food", 0.95),
    "BURGER KING":                          ("Burger King",     "Food", 0.99),
    "SUBWAY":                               ("Subway",          "Food", 0.99),
    "STARBUCKS":                            ("Starbucks",       "Food", 0.99),
    "TATA STARBUCKS":                       ("Starbucks",       "Food", 0.99),
    "CAFE COFFEE DAY":                      ("Café Coffee Day", "Food", 0.99),
    "COFFEE DAY":                           ("Café Coffee Day", "Food", 0.99),
    "CHAI POINT":                           ("Chai Point",      "Food", 0.99),
    "CHAI SUTTA BAR":                       ("Chai Sutta Bar",  "Food", 0.99),
    "HALDIRAMS":                            ("Haldiram's",      "Food", 0.99),
    "HALDIRAM SNACKS":                      ("Haldiram's",      "Food", 0.99),
    "BIKANER":                              ("Bikaner Sweets",  "Food", 0.90),
    "BIKANERWALA":                          ("Bikanerwala",     "Food", 0.99),
    "SARAVANA BHAVAN":                      ("Saravana Bhavan", "Food", 0.99),
    "HOTEL SARAVANA BHAVAN":                ("Saravana Bhavan", "Food", 0.99),
    "MTR FOODS":                            ("MTR Foods",       "Food", 0.90),
    "THEOBROMA":                            ("Theobroma",       "Food", 0.99),
    "NATURALS ICE CREAM":                   ("Naturals",        "Food", 0.95),
    "BASKIN ROBBINS":                       ("Baskin Robbins",  "Food", 0.99),
    "BARBEQUE NATION":                      ("Barbeque Nation", "Food", 0.99),
    "BOX8":                                 ("Box8",            "Food", 0.99),
    "BEHROUZ BIRYANI":                      ("Behrouz Biryani", "Food", 0.99),
    "FRESHMENU":                            ("FreshMenu",       "Food", 0.99),
    "FASOS":                                ("Faasos",          "Food", 0.99),
    "FAASOS":                               ("Faasos",          "Food", 0.99),
    "WENDY'S":                              ("Wendy's",         "Food", 0.99),
    "ROLL JUNCTION":                        ("Roll Junction",   "Food", 0.90),

    # ── Grocery / Supermarket ────────────────────────────────────────────────
    "AVENUE SUPERMARTS LTD":                ("DMart",           "Groceries", 0.99),
    "DMART AVENUE SUPERMARTS LTD":          ("DMart",           "Groceries", 0.99),
    "DMART":                                ("DMart",           "Groceries", 0.99),
    "BIGBASKET":                            ("BigBasket",       "Groceries", 0.99),
    "SUPERMARKET GROCERY SUPPLIES":         ("BigBasket",       "Groceries", 0.99),
    "MILKBASKET":                           ("Milkbasket",      "Groceries", 0.99),
    "RELIANCE FRESH":                       ("Reliance Fresh",  "Groceries", 0.99),
    "RELIANCE SMART":                       ("Reliance Smart",  "Groceries", 0.99),
    "RELIANCE RETAIL":                      ("Reliance Retail", "Groceries", 0.95),
    "ZEPTO":                                ("Zepto",           "Groceries", 0.99),
    "OTIPY":                                ("Otipy",           "Groceries", 0.95),
    "JIOMART":                              ("JioMart",         "Groceries", 0.99),
    "MORE SUPERMARKET":                     ("More Supermarket","Groceries", 0.99),
    "MORE RETAIL":                          ("More Retail",     "Groceries", 0.99),
    "SPENCER'S RETAIL":                     ("Spencer's",       "Groceries", 0.99),
    "SPENCERS":                             ("Spencer's",       "Groceries", 0.99),
    "SPAR":                                 ("SPAR",            "Groceries", 0.95),
    "STAR BAZAAR":                          ("Star Bazaar",     "Groceries", 0.99),
    "LULU HYPERMARKET":                     ("LuLu Hypermarket","Groceries", 0.99),
    "NATURE'S BASKET":                      ("Nature's Basket", "Groceries", 0.99),
    "EASYDAY":                              ("Easyday",         "Groceries", 0.95),
    "HERITAGE FRESH":                       ("Heritage Fresh",  "Groceries", 0.95),
    "NANDU'S CHICKEN":                      ("Nandu's Chicken", "Groceries", 0.90),
    "AMUL":                                 ("Amul",            "Groceries", 0.99),
    "MOTHER DAIRY":                         ("Mother Dairy",    "Groceries", 0.99),

    # ── Quick Commerce ───────────────────────────────────────────────────────
    "ZEPTO PAYMENT":                        ("Zepto",           "Groceries", 0.99),
    "BLINKIT TECHNOLOGIES":                 ("Blinkit",         "Groceries", 0.99),
    "SWIGGY INSTAMART":                     ("Swiggy Instamart","Groceries", 0.99),
    "INSTAMART":                            ("Swiggy Instamart","Groceries", 0.99),

    # ── Telecom / Recharge ───────────────────────────────────────────────────
    "MYJIO":                                ("Jio Recharge",    "Subscriptions", 0.99),
    "JIO":                                  ("Jio",             "Subscriptions", 0.95),
    "RELIANCE JIO INFOCOMM":                ("Jio",             "Subscriptions", 0.99),
    "AIRTEL":                               ("Airtel",          "Subscriptions", 0.99),
    "BHARTI AIRTEL":                        ("Airtel",          "Subscriptions", 0.99),
    "AIRTEL PAYMENTS BANK":                 ("Airtel Payments", "Finance", 0.90),
    "VODAFONE IDEA":                        ("Vi",              "Subscriptions", 0.99),
    "Vi":                                   ("Vi",              "Subscriptions", 0.99),
    "BSNL":                                 ("BSNL",            "Subscriptions", 0.99),
    "BHARAT SANCHAR NIGAM":                 ("BSNL",            "Subscriptions", 0.99),

    # ── Streaming / OTT ──────────────────────────────────────────────────────
    "NETFLIX ENTERTAINMENT SERVICES INDIA LLP": ("Netflix",     "Subscriptions", 0.99),
    "NETFLIX":                              ("Netflix",         "Subscriptions", 0.99),
    "SPOTIFY INDIA PVT LTD":               ("Spotify",         "Subscriptions", 0.99),
    "SPOTIFY":                              ("Spotify",         "Subscriptions", 0.99),
    "AMAZON PRIME":                         ("Amazon Prime",    "Subscriptions", 0.99),
    "PRIME MEMBERSHIP":                     ("Amazon Prime",    "Subscriptions", 0.99),
    "HOTSTAR":                              ("Disney+ Hotstar", "Subscriptions", 0.99),
    "DISNEY HOTSTAR":                       ("Disney+ Hotstar", "Subscriptions", 0.99),
    "STAR INDIA PRIVATE LIMITED":           ("Disney+ Hotstar", "Subscriptions", 0.99),
    "SONYLIV":                              ("SonyLIV",         "Subscriptions", 0.99),
    "SONY PICTURES NETWORKS":               ("SonyLIV",         "Subscriptions", 0.95),
    "ZEE5":                                 ("Zee5",            "Subscriptions", 0.99),
    "JIOSAAVN":                             ("JioSaavn",        "Subscriptions", 0.99),
    "YOUTUBE PREMIUM":                      ("YouTube Premium", "Subscriptions", 0.99),
    "GOOGLE":                               ("Google",          "Subscriptions", 0.85),
    "Google Play":                          ("Google Play",     "Entertainment", 0.95),
    "COSMOFEED":                            ("Cosmofeed",       "Subscriptions", 0.85),
    "MXPLAYER":                             ("MX Player",       "Subscriptions", 0.95),
    "ALT BALAJI":                           ("ALTBalaji",       "Subscriptions", 0.95),
    "ULLU":                                 ("Ullu",            "Subscriptions", 0.95),
    "LIONSGATE PLAY":                       ("Lionsgate Play",  "Subscriptions", 0.95),
    "APPLE":                                ("Apple",           "Subscriptions", 0.85),

    # ── E-Commerce ───────────────────────────────────────────────────────────
    "AMAZON":                               ("Amazon",          "Shopping", 0.90),
    "Amazon Pay on Delivery":               ("Amazon",          "Shopping", 0.90),
    "AMAZON SELLER SERVICES":               ("Amazon",          "Shopping", 0.99),
    "FLIPKART":                             ("Flipkart",        "Shopping", 0.99),
    "EKART":                                ("Flipkart Delivery","Shopping", 0.90),
    "MEESHO":                               ("Meesho",          "Shopping", 0.99),
    "FASHNEAR TECHNOLOGIES":                ("Meesho",          "Shopping", 0.99),
    "MYNTRA":                               ("Myntra",          "Shopping", 0.99),
    "AJIO":                                 ("AJIO",            "Shopping", 0.99),
    "RELIANCE BRANDS":                      ("Reliance Brands", "Shopping", 0.90),
    "NYKAA":                                ("Nykaa",           "Personal Care", 0.99),
    "FSN ECOMMERCE VENTURES":               ("Nykaa",           "Personal Care", 0.99),
    "TATA CLIQ":                            ("Tata CLiQ",       "Shopping", 0.99),
    "SNAPDEAL":                             ("Snapdeal",        "Shopping", 0.95),
    "SHOPCLUES":                            ("ShopClues",       "Shopping", 0.90),
    "CROMA":                                ("Croma",           "Tech / Devices", 0.99),
    "INFINITI RETAIL":                      ("Croma",           "Tech / Devices", 0.99),
    "VIJAY SALES":                          ("Vijay Sales",     "Tech / Devices", 0.99),
    "RELIANCE DIGITAL":                     ("Reliance Digital","Tech / Devices", 0.99),

    # ── Transport ────────────────────────────────────────────────────────────
    "PMPML":                                ("PMPML Bus",       "Transport", 0.99),
    "OLA":                                  ("Ola",             "Transport", 0.99),
    "ANI TECHNOLOGIES":                     ("Ola",             "Transport", 0.99),
    "UBER":                                 ("Uber",            "Transport", 0.99),
    "UBER INDIA":                           ("Uber",            "Transport", 0.99),
    "RAPIDO":                               ("Rapido",          "Transport", 0.99),
    "ROPPEN TRANSPORTATION SERVICES":       ("Rapido",          "Transport", 0.99),
    "BLUSMART":                             ("BluSmart",        "Transport", 0.99),
    "MERU":                                 ("Meru Cabs",       "Transport", 0.95),
    "INDIAN RAILWAY CATERING":              ("IRCTC",           "Transport", 0.99),
    "IRCTC":                                ("IRCTC",           "Transport", 0.99),
    "INDIGO":                               ("IndiGo",          "Transport", 0.99),
    "INTERGLOBE AVIATION":                  ("IndiGo",          "Transport", 0.99),
    "AIR INDIA":                            ("Air India",       "Transport", 0.99),
    "SPICEJET":                             ("SpiceJet",        "Transport", 0.99),
    "VISTARA":                              ("Vistara",         "Transport", 0.99),
    "AKASA AIR":                            ("Akasa Air",       "Transport", 0.99),
    "REDBUS":                               ("redBus",          "Transport", 0.99),
    "GHORADESHWAR PARKING":                 ("Parking",         "Transport", 0.99),
    "CAR PARKING":                          ("Parking",         "Transport", 0.99),
    "FASTAG":                               ("FASTag",          "Transport", 0.99),
    "IHMCL":                                ("FASTag/Toll",     "Transport", 0.99),

    # ── Fuel ─────────────────────────────────────────────────────────────────
    "KRUSHNAI PETROLEUM":                   ("Krushnai Petrol", "Petrol", 0.99),
    "KEDARI SERVICE STATION":               ("Kedari Petrol",   "Petrol", 0.99),
    "HIGHWAY PETROLEUM CENTRE":             ("Highway Petrol",  "Petrol", 0.99),
    "SIDDHARTH PETROLEUM":                  ("Siddharth Petrol","Petrol", 0.99),
    "COCO WARD ADHOC THREE S SERVICE STATION": ("Coco Petrol",  "Petrol", 0.95),
    "HPCL":                                 ("HPCL Fuel",       "Petrol", 0.99),
    "HINDUSTAN PETROLEUM":                  ("HPCL Fuel",       "Petrol", 0.99),
    "BPCL":                                 ("BPCL Fuel",       "Petrol", 0.99),
    "BHARAT PETROLEUM":                     ("BPCL Fuel",       "Petrol", 0.99),
    "IOCL":                                 ("Indian Oil",      "Petrol", 0.99),
    "INDIAN OIL":                           ("Indian Oil",      "Petrol", 0.99),
    "RELIANCE PETROLEUM":                   ("Reliance Petrol", "Petrol", 0.99),
    "ESSAR OIL":                            ("Essar Petrol",    "Petrol", 0.99),

    # ── Health / Pharmacy ────────────────────────────────────────────────────
    "APOLLO PHARMACY":                      ("Apollo Pharmacy", "Health", 0.99),
    "APOLLO HOSPITALS":                     ("Apollo Hospitals","Health", 0.99),
    "MEDPLUS":                              ("MedPlus",         "Health", 0.99),
    "MEDPLUS SOPAN BAUG":                   ("MedPlus",         "Health", 0.99),
    "1MG":                                  ("1mg",             "Health", 0.99),
    "TATA 1MG":                             ("1mg",             "Health", 0.99),
    "PHARMEASY":                            ("PharmEasy",       "Health", 0.99),
    "NETMEDS":                              ("Netmeds",         "Health", 0.99),
    "FORTIS":                               ("Fortis Hospital", "Health", 0.99),
    "MAX HEALTHCARE":                       ("Max Healthcare",  "Health", 0.99),
    "NARAYANA HEALTH":                      ("Narayana Health", "Health", 0.99),
    "DR LAL PATHLABS":                      ("Dr Lal PathLabs", "Health", 0.99),
    "SRL DIAGNOSTICS":                      ("SRL Diagnostics", "Health", 0.99),
    "THYROCARE":                            ("Thyrocare",       "Health", 0.99),
    "CULT FIT":                             ("Cult.fit",        "Health", 0.99),
    "CUREFIT":                              ("Cult.fit",        "Health", 0.99),
    "PRACTO":                               ("Practo",          "Health", 0.99),
    "HEALTHKART":                           ("HealthKart",      "Health", 0.99),
    "SHRI GANESH GENERIC MEDICINE STORE":   ("Shri Ganesh Pharmacy","Health", 0.99),
    "MEDICURE CHEMIST AND DRUGGIST":        ("Medicure Chemist","Health", 0.99),
    "HELTH LINE CEMIEST AND DRUGGIST":      ("Health Line Chemist","Health", 0.99),
    "VIGHNAHARTA PATHOLOGY LABORATORY":     ("Pathology Lab",   "Health", 0.99),
    "OM MEDICARE":                          ("Om Medicare",     "Health", 0.99),
    "JAY MALHAR MEDICAL":                   ("Jay Malhar Medical","Health", 0.99),
    "SHIVBA MEDICO 2":                      ("Shivba Medical",  "Health", 0.99),
    "JAY MAMTA MEDICAL":                    ("Jay Mamta Medical","Health", 0.99),
    "KISHOR CHEMIST AND SUPER MART":        ("Kishor Chemist",  "Health", 0.90),

    # ── Financial Services ───────────────────────────────────────────────────
    "ZERODHA":                              ("Zerodha",         "Finance", 0.99),
    "RAINMATTER TECHNOLOGIES":              ("Zerodha",         "Finance", 0.99),
    "GROWW":                                ("Groww",           "Finance", 0.99),
    "NEXTBILLION TECHNOLOGY":               ("Groww",           "Finance", 0.99),
    "UPSTOX":                               ("Upstox",          "Finance", 0.99),
    "RKSV SECURITIES":                      ("Upstox",          "Finance", 0.99),
    "ANGELBROKING":                         ("Angel One",       "Finance", 0.99),
    "ANGEL ONE":                            ("Angel One",       "Finance", 0.99),
    "PAYTM MONEY":                          ("Paytm Money",     "Finance", 0.99),
    "LIC":                                  ("LIC",             "Finance", 0.99),
    "LIFE INSURANCE CORPORATION":           ("LIC",             "Finance", 0.99),
    "HDFC LIFE":                            ("HDFC Life",       "Finance", 0.99),
    "SBI LIFE":                             ("SBI Life",        "Finance", 0.99),
    "ICICI PRUDENTIAL":                     ("ICICI Prudential","Finance", 0.99),
    "POLICYBAZAAR":                         ("Policybazaar",    "Finance", 0.95),
    "CRED":                                 ("CRED",            "Finance", 0.99),
    "DREAMPLUG TECHNOLOGIES":               ("CRED",            "Finance", 0.99),
    "SLICE":                                ("Slice",           "Finance", 0.95),
    "JUPITER MONEY":                        ("Jupiter",         "Finance", 0.95),
    "FI MONEY":                             ("Fi Money",        "Finance", 0.95),
    "NIYO":                                 ("Niyo",            "Finance", 0.95),
    "PAYTM":                                ("Paytm",           "Finance", 0.90),
    "ONE97 COMMUNICATIONS":                 ("Paytm",           "Finance", 0.90),

    # ── Travel & Accommodation ───────────────────────────────────────────────
    "MAKEMYTRIP":                           ("MakeMyTrip",      "Transport", 0.99),
    "MAKE MY TRIP":                         ("MakeMyTrip",      "Transport", 0.99),
    "OYO":                                  ("OYO",             "Transport", 0.99),
    "ORAVEL STAYS":                         ("OYO",             "Transport", 0.99),
    "GOIBIBO":                              ("Goibibo",         "Transport", 0.99),
    "YATRA":                                ("Yatra",           "Transport", 0.99),
    "CLEARTRIP":                            ("Cleartrip",       "Transport", 0.99),
    "IXIGO":                                ("ixigo",           "Transport", 0.99),
    "ABHIBUS":                              ("AbhiBus",         "Transport", 0.99),
    "TREEBO":                               ("Treebo Hotels",   "Transport", 0.95),
    "FABHOTELS":                            ("FabHotels",       "Transport", 0.95),

    # ── Clothing / Fashion ───────────────────────────────────────────────────
    "SNITCH APPARELS PRIVATE LIMITED":      ("Snitch",          "Clothing", 0.99),
    "HENNES N MAURITZ":                     ("H&M",             "Clothing", 0.99),
    "H&M":                                  ("H&M",             "Clothing", 0.99),
    "ZARA":                                 ("Zara",            "Clothing", 0.99),
    "UNIQLO":                               ("Uniqlo",          "Clothing", 0.99),
    "MANGO":                                ("Mango",           "Clothing", 0.99),
    "PANTALOONS":                           ("Pantaloons",      "Clothing", 0.99),
    "LIFESTYLE STORES":                     ("Lifestyle",       "Clothing", 0.99),
    "SHOPPERS STOP":                        ("Shoppers Stop",   "Clothing", 0.99),
    "WESTSIDE":                             ("Westside",        "Clothing", 0.99),
    "MAX FASHION":                          ("Max Fashion",     "Clothing", 0.99),
    "FABINDIA":                             ("FabIndia",        "Clothing", 0.99),
    "BIBA":                                 ("Biba",            "Clothing", 0.99),
    "W FOR WOMAN":                          ("W",               "Clothing", 0.95),
    "ALLEN SOLLY":                          ("Allen Solly",     "Clothing", 0.99),
    "PETER ENGLAND":                        ("Peter England",   "Clothing", 0.99),
    "VAN HEUSEN":                           ("Van Heusen",      "Clothing", 0.99),
    "LEVI'S":                               ("Levi's",          "Clothing", 0.99),
    "LEVIS":                                ("Levi's",          "Clothing", 0.99),
    "DECATHLON":                            ("Decathlon",       "Clothing", 0.99),
    "RIVAN COLLECTION":                     ("Rivan Collection","Clothing", 0.90),
    "SHRI BALAJI COLLECTION":               ("Balaji Collection","Clothing", 0.85),

    # ── Education ────────────────────────────────────────────────────────────
    "MIT UNIVERSITY":                       ("MIT University",  "Education", 0.99),
    "MIT ADT XEROX AND STATIONARY":         ("MIT Stationery",  "Stationery", 0.95),
    "ITVEDANT":                             ("ITVedant",        "Education", 0.90),
    "BYJU'S":                               ("BYJU'S",          "Education", 0.99),
    "BYJUS":                                ("BYJU'S",          "Education", 0.99),
    "THINK AND LEARN":                      ("BYJU'S",          "Education", 0.99),
    "UNACADEMY":                            ("Unacademy",       "Education", 0.99),
    "SORTING HAT TECHNOLOGIES":             ("Unacademy",       "Education", 0.99),
    "VEDANTU":                              ("Vedantu",         "Education", 0.99),
    "UPGRAD":                               ("upGrad",          "Education", 0.99),
    "COURSERA":                             ("Coursera",        "Education", 0.99),
    "UDEMY":                                ("Udemy",           "Education", 0.99),
    "SKILLSHARE":                           ("Skillshare",      "Education", 0.99),
    "WHITEHAT JR":                          ("WhiteHat Jr",     "Education", 0.99),
    "PHYSICSWALLAH":                        ("PhysicsWallah",   "Education", 0.99),
    "PW SKILLS":                            ("PW Skills",       "Education", 0.99),
    "SIMPLILEARN":                          ("Simplilearn",     "Education", 0.99),
    "EVENTBEEP TECHNOSERVICES PRIVATE LIMITED": ("EventBeep",   "Education", 0.75),

    # ── Tech / Devices ───────────────────────────────────────────────────────
    "AWS INDIA":                            ("AWS",             "Tech / Devices", 0.99),
    "AMAZON WEB SERVICES":                  ("AWS",             "Tech / Devices", 0.99),
    "GOOGLE CLOUD":                         ("Google Cloud",    "Tech / Devices", 0.99),
    "MICROSOFT":                            ("Microsoft",       "Tech / Devices", 0.90),
    "GITHUB":                               ("GitHub",          "Tech / Devices", 0.99),
    "DIGITALOCEAN":                         ("DigitalOcean",    "Tech / Devices", 0.99),
    "A TECH COMPUTERS":                     ("A Tech Computers","Tech / Devices", 0.90),
    "DOMAIN":                               ("Domain/Hosting",  "Tech / Devices", 0.75),
    "GODADDY":                              ("GoDaddy",         "Tech / Devices", 0.99),
    "NAMECHEAP":                            ("Namecheap",       "Tech / Devices", 0.99),

    # ── Entertainment ────────────────────────────────────────────────────────
    "DISTRICT MOVIE TICKET":                ("District App",    "Entertainment", 0.99),
    "ORBGEN TECHNOLOGIES PRIVATE LIMITED DISTRICT MOVIE UPI": ("District App", "Entertainment", 0.99),
    "BOOKMYSHOW":                           ("BookMyShow",      "Entertainment", 0.99),
    "BIGTREE ENTERTAINMENT":                ("BookMyShow",      "Entertainment", 0.99),
    "PAYTM MOVIES":                         ("Paytm Movies",    "Entertainment", 0.99),
    "INOX":                                 ("INOX Cinemas",    "Entertainment", 0.99),
    "PVR":                                  ("PVR Cinemas",     "Entertainment", 0.99),
    "PVR INOX":                             ("PVR INOX",        "Entertainment", 0.99),
    "CINEPOLIS":                            ("Cinepolis",       "Entertainment", 0.99),
    "DREAM11":                              ("Dream11",         "Entertainment", 0.99),
    "DREAM SPORTS":                         ("Dream11",         "Entertainment", 0.99),
    "MPL":                                  ("MPL",             "Entertainment", 0.99),
    "MY11CIRCLE":                           ("My11Circle",      "Entertainment", 0.95),
    "SB GAME GALAXY":                       ("Game Galaxy",     "Entertainment", 0.90),
    "ROOTER SPORTS TECHNOLOGIES PRIVATE LIMITED": ("Rooter",    "Entertainment", 0.90),
    "STEAM":                                ("Steam",           "Entertainment", 0.99),
    "SONY PLAYSTATION":                     ("PlayStation",     "Entertainment", 0.99),

    # ── Personal Care ────────────────────────────────────────────────────────
    "MAMAEARTH":                            ("Mamaearth",       "Personal Care", 0.99),
    "HONASA CONSUMER":                      ("Mamaearth",       "Personal Care", 0.99),
    "PLUM GOODNESS":                        ("Plum",            "Personal Care", 0.99),
    "WOW SKIN SCIENCE":                     ("Wow Skin",        "Personal Care", 0.99),
    "LAKME":                                ("Lakmé",           "Personal Care", 0.99),
    "L'OREAL":                              ("L'Oréal",         "Personal Care", 0.99),
    "LOREAL":                               ("L'Oréal",         "Personal Care", 0.99),
    "HEADS UP FOR TAILS":                   ("Heads Up For Tails","Personal Care",0.95),
    "SUGAR COSMETICS":                      ("Sugar Cosmetics", "Personal Care", 0.99),
    "PURPLLE":                              ("Purplle",         "Personal Care", 0.99),

    # ── Utilities ────────────────────────────────────────────────────────────
    "MSEB":                                 ("MSEB Electricity","Utilities", 0.99),
    "MSEDCL":                               ("MSEDCL",          "Utilities", 0.99),
    "TATA POWER":                           ("Tata Power",      "Utilities", 0.99),
    "ADANI ELECTRICITY":                    ("Adani Electricity","Utilities", 0.99),
    "BESCOM":                               ("BESCOM",          "Utilities", 0.99),
    "BWSSB":                                ("BWSSB Water",     "Utilities", 0.99),
    "MAHANAGAR GAS":                        ("Mahanagar Gas",   "Utilities", 0.99),
    "INDRAPRASTHA GAS":                     ("IGL Gas",         "Utilities", 0.99),
    "GUJARAT GAS":                          ("Gujarat Gas",     "Utilities", 0.99),
    "JUST DIAL":                            ("JustDial",        "Utilities", 0.85),
    "SULEKHA":                              ("Sulekha",         "Utilities", 0.80),
    "URBAN COMPANY":                        ("Urban Company",   "Utilities", 0.99),
    "URBANCLAP":                            ("Urban Company",   "Utilities", 0.99),

    # ── Stationery ───────────────────────────────────────────────────────────
    "SARASWATI STATIONERY GENERAL STORES":  ("Saraswati Stationery","Stationery", 0.99),
    "SARSWATI STATIONERY AND GENRAL STORES":("Saraswati Stationery","Stationery", 0.99),
    "JK STATIONERY":                        ("JK Stationery",  "Stationery", 0.99),
    "YASH COPIERS":                         ("Yash Copiers",   "Stationery", 0.99),
    "NET ZONE CYBER CAFE":                  ("Net Zone Cyber Cafe","Stationery",0.85),

    # ── Local merchants already in DB (Pune-specific) ────────────────────────
    "KSHITIJ KHADE":                        ("Kshitij Khade",  "P2P Transfer", 0.50),
    "SARIKA INJANWARE":                     ("Sarika Injanware","P2P Transfer", 0.50),
    "SUVARNA GOPAL SRINIWAS":               ("Suvarna Sriniwas","P2P Transfer", 0.50),
}
# fmt: on


def normalize_merchant(raw_name: str, threshold: int = 80) -> tuple[str, str, float]:
    """
    Fuzzy-match raw merchant name against KNOWN_MERCHANTS.
    Returns (clean_name, category, confidence).
    Falls through to ('Other', 0.40) when no match above threshold.
    """
    raw_upper = raw_name.upper().strip()
    best_score = 0
    best_match: tuple[str, str, float] | None = None

    for known, (clean, category, conf) in KNOWN_MERCHANTS.items():
        score = fuzz.token_sort_ratio(raw_upper, known.upper())
        if score > best_score:
            best_score = score
            best_match = (clean, category, conf)

    if best_score >= threshold and best_match:
        clean, category, base_conf = best_match
        return clean, category, round(base_conf * (best_score / 100), 2)

    return raw_name, "Other", 0.40
